In [1]:
import pandas as pd
import os

In [2]:
df=pd.read_csv('table-a-housing-development-applications-submitted.csv')
df

C:\Users\leond\AppData\Local\Temp\ipykernel_13664\594250855.py:1: DtypeWarning: Columns (4,6,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('table-a-housing-development-applications-submitted.csv')

,JURS_NAME,CNTY_NAME,YEAR,APN,PRIOR_APN,STREET_ADDRESS,PROJECT_NAME,JURS_TRACKING_ID,UNIT_CAT,TENURE,...,MOD_INCOME_NDR,ABOVE_MOD_INCOME,TOT_PROPOSED_UNITS,TOT_APPROVED_UNITS,TOT_DISAPPROVED_UNITS,APP_SUBMITTED_SB35,DENSITY_BONUS_RECEIVED,DENSITY_BONUS_APPROVED,APPLICATION_STATUS,NOTES
0,RIVERSIDE COUNTY,RIVERSIDE,2021,461190072,NaN,NaN,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,No,Approved,NaN
1,RIVERSIDE COUNTY,RIVERSIDE,2021,461190072,NaN,NaN,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,No,Approved,NaN
2,RIVERSIDE COUNTY,RIVERSIDE,2021,461190072,NaN,NaN,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,No,Approved,NaN
3,RIVERSIDE COUNTY,RIVERSIDE,2021,461190072,NaN,NaN,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,No,Approved,NaN
4,RIVERSIDE COUNTY,RIVERSIDE,2021,461190072,NaN,NaN,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,No,Approved,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153617,SAN BERNARDINO COUNTY,SAN BERNARDINO,2019,3.57551E+11,NaN,"5980 CORIANDER DR, OAK HILLS, CA 92344",NaN,SFR-2019-00393,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,see note above (cell T13)
153618,SAN BERNARDINO COUNTY,SAN BERNARDINO,2019,2.32842E+12,NaN,"1260 FOX FARM RD, BIG BEAR LAKE, CA 92315",NaN,SFR-2019-00531,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,see note above (cell T13)
153619,SAN BERNARDINO COUNTY,SAN BERNARDINO,2019,3.04041E+11,NaN,"1325 WEST MIRALAGO TR, FAWNSKIN, CA 92333",NaN,SFR-2019-00109,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,see note above (cell T13)
153620,SAN BERNARDINO COUNTY,SAN BERNARDINO,2019,5.94151E+11,NaN,"5757 SERRANO RD, PIONEERTOWN, CA 92268",NaN,SFR-2019-00739,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,see note above (cell T13)
153621,SAN BERNARDINO COUNTY,SAN BERNARDINO,2019,3.57651E+11,NaN,"6504 BALDY MESA RD, PHELAN, CA 92371",NaN,SFR-2019-00589,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,see note above (cell T13)

In [3]:
df['CNTY_NAME'].unique()

array(['RIVERSIDE', 'SAN BERNARDINO', 'MENDOCINO', 'ALAMEDA',
       'CONTRA COSTA', 'VENTURA', 'SANTA CLARA', 'ORANGE', 'SHASTA',
       'SAN LUIS OBISPO', 'SAN BENITO', 'SAN MATEO', 'LOS ANGELES',
       'MADERA', 'SAN DIEGO', 'TUOLUMNE', 'CALAVERAS', 'HUMBOLDT',
       'SANTA BARBARA', 'MARIN', 'TRINITY', 'SISKIYOU', 'SANTA CRUZ',
       'SONOMA', 'NAPA', 'KERN', 'MONTEREY', 'SOLANO', 'MONO',
       'STANISLAUS', 'LAKE', 'FRESNO', 'COLUSA', 'SAN JOAQUIN', 'MERCED',
       'DEL NORTE', 'PLACER', 'KINGS', 'EL DORADO', 'TULARE',
       'SACRAMENTO', 'IMPERIAL', 'AMADOR', 'INYO', 'BUTTE', 'YOLO',
       'GLENN', 'SUTTER', 'PLUMAS', 'NEVADA', 'YUBA', 'TEHAMA', 'LASSEN',
       'SAN FRANCISCO', 'SIERRA', 'ALPINE', 'MODOC', 'MARIPOSA'],
      dtype=object)

In [5]:
df.drop(df[df['CNTY_NAME'] != 'LOS ANGELES'].index, inplace=True)
df

,JURS_NAME,CNTY_NAME,YEAR,APN,PRIOR_APN,STREET_ADDRESS,PROJECT_NAME,JURS_TRACKING_ID,UNIT_CAT,TENURE,...,MOD_INCOME_NDR,ABOVE_MOD_INCOME,TOT_PROPOSED_UNITS,TOT_APPROVED_UNITS,TOT_DISAPPROVED_UNITS,APP_SUBMITTED_SB35,DENSITY_BONUS_RECEIVED,DENSITY_BONUS_APPROVED,APPLICATION_STATUS,NOTES
4545,CULVER CITY,LOS ANGELES,2021,4209-001-015,NaN,4075 Jackson,NaN,NaN,Single-Family Attached Unit,Renter,...,0,1,1,1,0,No,No,NaN,Approved,NaN
4546,SIERRA MADRE,LOS ANGELES,2021,5768-033-037,NaN,181 S Sunnyside,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,NaN,Approved,NaN
4547,SIERRA MADRE,LOS ANGELES,2021,5762-012-008,NaN,62 E Carter,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,NaN,Approved,NaN
4548,HIDDEN HILLS,LOS ANGELES,2021,2049-045-004,NaN,24105 Hidden Ridge Rd,NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,NaN,Approved,NaN
4549,MANHATTAN BEACH,LOS ANGELES,2021,4177027015,NaN,"124 23RD PL #B\r\nMANHATTAN BEACH, CA",NaN,NaN,Single-Family Detached Unit,Owner,...,0,1,1,1,0,No,No,No,Approved,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152497,LA PUENTE,LOS ANGELES,2020,8214-018-007,NaN,369 Maypop Ave.,NaN,NaN,Accessory Dwelling Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,Convert [E] two-car garage into ADU
152498,LA PUENTE,LOS ANGELES,2020,8263-021-006,NaN,16813 Maclaren St.,NaN,NaN,Accessory Dwelling Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,Convert [E] two-car garage into ADU
152499,LA PUENTE,LOS ANGELES,2020,8247-018-036,NaN,16260 Bamboo St,NaN,NaN,Accessory Dwelling Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,Convert [E] two-car garage into ADU
152500,LA PUENTE,LOS ANGELES,2020,8213-004-008,NaN,15237 Homeward St,NaN,NaN,Accessory Dwelling Unit,Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,[N] Integrated ADU
152501,WEST HOLLYWOOD,LOS ANGELES,2020,4340014003,NaN,732 DOHENY DR,NaN,NaN,"2-, 3-, and 4-Plex Units per Structure",Owner,...,0,1,1,1,0,No,NaN,NaN,NaN,Applied 11/12/2020

In [6]:
counts = df.isna().sum()
print(counts.sort_values(ascending=False))

NOTES                     45276
PRIOR_APN                 44944
DENSITY_BONUS_APPROVED    35948
PROJECT_NAME              35804
APPLICATION_STATUS        33094
DENSITY_BONUS_RECEIVED    33094
JURS_TRACKING_ID           8375
STREET_ADDRESS              292
APN                         259
MOD_INCOME_NDR                0
APP_SUBMITTED_SB35            0
TOT_DISAPPROVED_UNITS         0
TOT_APPROVED_UNITS            0
TOT_PROPOSED_UNITS            0
ABOVE_MOD_INCOME              0
JURS_NAME                     0
MOD_INCOME_DR                 0
LOW_INCOME_NDR                0
CNTY_NAME                     0
VLOW_INCOME_NDR               0
VLOW_INCOME_DR                0
APP_SUBMIT_DT                 0
TENURE                        0
UNIT_CAT                      0
YEAR                          0
LOW_INCOME_DR                 0
dtype: int64

In [7]:
df.drop(columns=['NOTES', 'PRIOR_APN'], inplace=True)

In [8]:
uniquy = df.nunique()
print(uniquy.sort_values(ascending=True))

CNTY_NAME                     1
DENSITY_BONUS_RECEIVED        2
DENSITY_BONUS_APPROVED        2
TENURE                        2
YEAR                          4
APP_SUBMITTED_SB35            4
VLOW_INCOME_NDR               5
APPLICATION_STATUS            5
UNIT_CAT                      6
LOW_INCOME_NDR                7
MOD_INCOME_NDR               29
MOD_INCOME_DR                37
TOT_DISAPPROVED_UNITS        49
JURS_NAME                    83
VLOW_INCOME_DR               96
LOW_INCOME_DR               118
TOT_APPROVED_UNITS          174
ABOVE_MOD_INCOME            315
TOT_PROPOSED_UNITS          337
APP_SUBMIT_DT              1399
PROJECT_NAME              10562
JURS_TRACKING_ID          38365
APN                       42415
STREET_ADDRESS            45151
dtype: int64

In [16]:
df.to_csv('a_clean.csv', index=False)