In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('A&A2MERGED.CSV', low_memory=False)
df

,JURS_NAME_x,CNTY_NAME_x,YEAR_x,APN_x,STREET_ADDRESS,JURS_TRACKING_ID_x,UNIT_CAT_DESC,TENURE_DESC,VLOW_INCOME_DR_x,VLOW_INCOME_NDR_x,...,MOD_INCOME_DR_y,MOD_INCOME_NDR_y,ABOVE_MOD_INCOME_y,TOT_PROPOSED_UNITS,TOT_APPROVED_UNITS,TOT_DISAPPROVED_UNITS,APP_SUBMITTED_SB35,DENSITY_BONUS_RECEIVED,DENSITY_BONUS_APPROVED,APPLICATION_STATUS
0,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
1,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
2,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,0,0,No,NaN,NaN,NaN
3,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,0,0,No,NaN,NaN,NaN
4,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Accessory Dwelling Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90209,LOS ANGELES,LOS ANGELES,2021,5141001903,619 S WESTLAKE AVE,19010-10000-05735,5 or More Units Per Structure,Renter,0,0,...,0,0,78,78,0,0,No,NaN,NaN,NaN
90210,LOS ANGELES,LOS ANGELES,2021,5094026018,904 S NEW HAMPSHIRE AVE,19010-10000-04314,5 or More Units Per Structure,Renter,0,0,...,0,0,53,63,0,0,No,NaN,NaN,NaN
90211,LOS ANGELES,LOS ANGELES,2021,5538012013,1040 N KENMORE AVE,19010-10000-05573,5 or More Units Per Structure,Renter,0,0,...,0,0,62,62,0,0,No,NaN,NaN,NaN
90212,LOS ANGELES,LOS ANGELES,2021,5183001017,2025 E NEW JERSEY ST,18010-10000-04650,5 or More Units Per Structure,Renter,0,0,...,0,0,15,15,0,0,No,NaN,NaN,NaN
90213,HAWTHORNE,LOS ANGELES,2021,4052-021-017,13927 Chadron Ave,BLDG00-5540,5 or More Units Per Structure,Renter,0,0,...,0,0,6,7,7,0,No,NaN,NaN,NaN

In [4]:
df = df.assign(v_low=df['VLOW_INCOME_DR_x'] + df['VLOW_INCOME_DR_y'] + df['VLOW_INCOME_NDR_x'] + df['VLOW_INCOME_NDR_y'] + df['BP_VLOW_INCOME_DR'] + df['BP_VLOW_INCOME_NDR'] )

In [5]:
df.drop(columns=['VLOW_INCOME_DR_x', 'VLOW_INCOME_DR_y', 'VLOW_INCOME_NDR_y', 'VLOW_INCOME_NDR_x', 'BP_VLOW_INCOME_DR', 'BP_VLOW_INCOME_NDR'], inplace=True)

In [6]:
df = df.assign(low=df['LOW_INCOME_DR_x'] + df['LOW_INCOME_DR_y'] + df['LOW_INCOME_NDR_x'] + df['LOW_INCOME_NDR_y'] + df['BP_LOW_INCOME_DR'] + df['BP_LOW_INCOME_NDR'] )

In [7]:
df.drop(columns=['LOW_INCOME_DR_x', 'LOW_INCOME_DR_y', 'LOW_INCOME_NDR_y', 'LOW_INCOME_NDR_x', 'BP_LOW_INCOME_DR', 'BP_LOW_INCOME_NDR'], inplace=True)

In [8]:
df = df.assign(mod=df['MOD_INCOME_DR_x'] + df['MOD_INCOME_DR_y'] + df['MOD_INCOME_NDR_x'] + df['MOD_INCOME_NDR_y'] + df['BP_MOD_INCOME_DR'] + df['BP_MOD_INCOME_NDR'] )

In [9]:
df.drop(columns=['MOD_INCOME_DR_x', 'MOD_INCOME_DR_y', 'MOD_INCOME_NDR_x', 'MOD_INCOME_NDR_y', 'BP_MOD_INCOME_DR', 'BP_MOD_INCOME_NDR'], inplace=True)

In [10]:
df = df.assign(above=df['ABOVE_MOD_INCOME_x'] + df['ABOVE_MOD_INCOME_y'] + df['BP_ABOVE_MOD_INCOME'] )

In [11]:
df.drop(columns=['ABOVE_MOD_INCOME_x', 'ABOVE_MOD_INCOME_y', 'BP_ABOVE_MOD_INCOME'], inplace=True)

In [12]:
df.to_csv('A&A2MERGED.CSV', index=False)