In [1]:
import pandas as pd
import os

In [2]:
df1 = pd.read_csv('a_clean.csv')
df2 = pd.read_csv('a2_clean.csv')

C:\Users\leond\AppData\Local\Temp\ipykernel_34800\3434271138.py:2: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('a2_clean.csv')

In [3]:
df12 = pd.merge(df2, df1, on="STREET_ADDRESS")

In [4]:
df12

,JURS_NAME_x,CNTY_NAME_x,YEAR_x,APN_x,STREET_ADDRESS,JURS_TRACKING_ID_x,UNIT_CAT_DESC,TENURE_DESC,VLOW_INCOME_DR_x,VLOW_INCOME_NDR_x,...,MOD_INCOME_DR_y,MOD_INCOME_NDR_y,ABOVE_MOD_INCOME_y,TOT_PROPOSED_UNITS,TOT_APPROVED_UNITS,TOT_DISAPPROVED_UNITS,APP_SUBMITTED_SB35,DENSITY_BONUS_RECEIVED,DENSITY_BONUS_APPROVED,APPLICATION_STATUS
0,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
1,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
2,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,0,0,No,NaN,NaN,NaN
3,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,0,0,No,NaN,NaN,NaN
4,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Accessory Dwelling Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90209,LOS ANGELES,LOS ANGELES,2021,5141001903,619 S WESTLAKE AVE,19010-10000-05735,5 or More Units Per Structure,Renter,0,0,...,0,0,78,78,0,0,No,NaN,NaN,NaN
90210,LOS ANGELES,LOS ANGELES,2021,5094026018,904 S NEW HAMPSHIRE AVE,19010-10000-04314,5 or More Units Per Structure,Renter,0,0,...,0,0,53,63,0,0,No,NaN,NaN,NaN
90211,LOS ANGELES,LOS ANGELES,2021,5538012013,1040 N KENMORE AVE,19010-10000-05573,5 or More Units Per Structure,Renter,0,0,...,0,0,62,62,0,0,No,NaN,NaN,NaN
90212,LOS ANGELES,LOS ANGELES,2021,5183001017,2025 E NEW JERSEY ST,18010-10000-04650,5 or More Units Per Structure,Renter,0,0,...,0,0,15,15,0,0,No,NaN,NaN,NaN
90213,HAWTHORNE,LOS ANGELES,2021,4052-021-017,13927 Chadron Ave,BLDG00-5540,5 or More Units Per Structure,Renter,0,0,...,0,0,6,7,7,0,No,NaN,NaN,NaN

In [5]:
df12.to_csv('A&A2MERGED.CSV', index=False)