In [8]:
import os
import pandas as pd

In [9]:
df1= pd.read_csv('a_clean.csv')
df2= pd.read_csv('a2_clean.csv')

C:\Users\leond\AppData\Local\Temp\ipykernel_25160\1278313880.py:2: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2= pd.read_csv('a2_clean.csv')

In [10]:
df1

,JURS_NAME,CNTY_NAME,YEAR,APN,STREET_ADDRESS,PROJECT_NAME,JURS_TRACKING_ID,UNIT_CAT,TENURE,APP_SUBMIT_DT,...,MOD_INCOME_DR,MOD_INCOME_NDR,ABOVE_MOD_INCOME,TOT_PROPOSED_UNITS,TOT_APPROVED_UNITS,TOT_DISAPPROVED_UNITS,APP_SUBMITTED_SB35,DENSITY_BONUS_RECEIVED,DENSITY_BONUS_APPROVED,APPLICATION_STATUS
0,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,NaN,Single-Family Attached Unit,Renter,6/23/2021,...,0,0,1,1,1,0,No,No,NaN,Approved
1,SIERRA MADRE,LOS ANGELES,2021,5768-033-037,181 S Sunnyside,NaN,NaN,Single-Family Detached Unit,Owner,5/19/2021,...,0,0,1,1,1,0,No,No,NaN,Approved
2,SIERRA MADRE,LOS ANGELES,2021,5762-012-008,62 E Carter,NaN,NaN,Single-Family Detached Unit,Owner,6/14/2021,...,0,0,1,1,1,0,No,No,NaN,Approved
3,HIDDEN HILLS,LOS ANGELES,2021,2049-045-004,24105 Hidden Ridge Rd,NaN,NaN,Single-Family Detached Unit,Owner,4/20/2021,...,0,0,1,1,1,0,No,No,NaN,Approved
4,MANHATTAN BEACH,LOS ANGELES,2021,4177027015,"124 23RD PL #B\r\nMANHATTAN BEACH, CA",NaN,NaN,Single-Family Detached Unit,Owner,5/26/2021,...,0,0,1,1,1,0,No,No,No,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47977,LA PUENTE,LOS ANGELES,2020,8214-018-007,369 Maypop Ave.,NaN,NaN,Accessory Dwelling Unit,Owner,12/3/2020,...,0,0,1,1,1,0,No,NaN,NaN,NaN
47978,LA PUENTE,LOS ANGELES,2020,8263-021-006,16813 Maclaren St.,NaN,NaN,Accessory Dwelling Unit,Owner,12/8/2020,...,0,0,1,1,1,0,No,NaN,NaN,NaN
47979,LA PUENTE,LOS ANGELES,2020,8247-018-036,16260 Bamboo St,NaN,NaN,Accessory Dwelling Unit,Owner,12/10/2020,...,0,0,1,1,1,0,No,NaN,NaN,NaN
47980,LA PUENTE,LOS ANGELES,2020,8213-004-008,15237 Homeward St,NaN,NaN,Accessory Dwelling Unit,Owner,4/13/2020,...,0,0,1,1,1,0,No,NaN,NaN,NaN
47981,WEST HOLLYWOOD,LOS ANGELES,2020,4340014003,732 DOHENY DR,NaN,NaN,"2-, 3-, and 4-Plex Units per Structure",Owner,11/12/2020,...,0,0,1,1,1,0,No,NaN,NaN,NaN

In [11]:
df_merged = pd.merge(df2, df1, on='STREET_ADDRESS')

In [12]:
df_merged

,JURS_NAME_x,CNTY_NAME_x,YEAR_x,APN_x,STREET_ADDRESS,JURS_TRACKING_ID_x,UNIT_CAT_DESC,TENURE_DESC,VLOW_INCOME_DR_x,VLOW_INCOME_NDR_x,...,MOD_INCOME_DR_y,MOD_INCOME_NDR_y,ABOVE_MOD_INCOME_y,TOT_PROPOSED_UNITS,TOT_APPROVED_UNITS,TOT_DISAPPROVED_UNITS,APP_SUBMITTED_SB35,DENSITY_BONUS_RECEIVED,DENSITY_BONUS_APPROVED,APPLICATION_STATUS
0,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
1,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
2,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,0,0,No,NaN,NaN,NaN
3,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Single-Family Attached Unit,Renter,0,0,...,0,0,1,1,0,0,No,NaN,NaN,NaN
4,CULVER CITY,LOS ANGELES,2021,4209-001-015,4075 Jackson,NaN,Accessory Dwelling Unit,Renter,0,0,...,0,0,1,1,1,0,No,No,NaN,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90209,LOS ANGELES,LOS ANGELES,2021,5141001903,619 S WESTLAKE AVE,19010-10000-05735,5 or More Units Per Structure,Renter,0,0,...,0,0,78,78,0,0,No,NaN,NaN,NaN
90210,LOS ANGELES,LOS ANGELES,2021,5094026018,904 S NEW HAMPSHIRE AVE,19010-10000-04314,5 or More Units Per Structure,Renter,0,0,...,0,0,53,63,0,0,No,NaN,NaN,NaN
90211,LOS ANGELES,LOS ANGELES,2021,5538012013,1040 N KENMORE AVE,19010-10000-05573,5 or More Units Per Structure,Renter,0,0,...,0,0,62,62,0,0,No,NaN,NaN,NaN
90212,LOS ANGELES,LOS ANGELES,2021,5183001017,2025 E NEW JERSEY ST,18010-10000-04650,5 or More Units Per Structure,Renter,0,0,...,0,0,15,15,0,0,No,NaN,NaN,NaN
90213,HAWTHORNE,LOS ANGELES,2021,4052-021-017,13927 Chadron Ave,BLDG00-5540,5 or More Units Per Structure,Renter,0,0,...,0,0,6,7,7,0,No,NaN,NaN,NaN

In [13]:
counts = df_merged.isna().sum()
print(counts.sort_values(ascending=False))

CO_ISSUE_DT1              82273
DENSITY_BONUS_APPROVED    77620
BP_ISSUE_DT1              67687
APPLICATION_STATUS        67027
DENSITY_BONUS_RECEIVED    67027
                          ...
CO_VLOW_INCOME_NDR            0
CO_LOW_INCOME_DR              0
CO_LOW_INCOME_NDR             0
CNTY_NAME_x                   0
CO_MOD_INCOME_DR              0
Length: 61, dtype: int64

In [7]:
df_merged.to_csv('merged.csv', index=False)